import { CuratedItem, GutenbergSource } from './types';

export const curatedDB: CuratedItem[] = [
  // Criminal Minds
  { text: "Before you embark on a journey of revenge, dig two graves.", source: "Criminal Minds", type: "drama" },
  { text: "I don't believe that intelligence can be accurately quantified, but I do have an IQ of 187, an eidetic memory, and can read 20,000 words per minute.", source: "Criminal Minds", type: "drama" },
  { text: "Finding new ways to hurt each other is what we're good at.", source: "Criminal Minds", type: "drama" },
  { text: "It's not a needle in a haystack. We're looking for a particular needle in a pile of needles.", source: "Criminal Minds", type: "drama" },
  { text: "They don't call them nervous breakdowns anymore.", source: "Criminal Minds", type: "drama" },
  { text: "Ideologies separate us. Dreams and anguish bring us together.", source: "Criminal Minds", type: "drama" },
  { text: "All through history, there have been tyrants and murderers, and for a time they can seem invincible, but in the end they always fall. Always.", source: "Criminal Minds", type: "drama" },
  { text: "In order to learn the important lessons in life, one must each day surmount a fear.", source: "Criminal Minds", type: "drama" },
  { text: "Between the idea and the reality, between the motion and the act, falls the shadow.", source: "Criminal Minds", type: "drama" },
  { text: "Monsters are real, and ghosts are real too. They live inside us, and sometimes they win.", source: "Criminal Minds", type: "drama" },
  { text: "Fantasy abandoned by reason produces impossible monsters.", source: "Criminal Minds", type: "drama" },
  { text: "No matter how dark the moment, love and hope are always possible.", source: "Criminal Minds", type: "drama" },
  { text: "In order for the light to shine so brightly, the darkness must be present.", source: "Criminal Minds", type: "drama" },
  { text: "There's no tragedy in life like the death of a child. Things never get back to the way they were.", source: "Criminal Minds", type: "drama" },
  { text: "No mortal can keep a secret. If his lips are silent, he chatters with his fingertips; betrayal oozes out of him at every pore.", source: "Criminal Minds", type: "drama" },
  { text: "Without a family, man, alone in the world, trembles with the cold.", source: "Criminal Minds", type: "drama" },
  { text: "Find the place inside where there's joy, and the joy will burn out the pain.", source: "Criminal Minds", type: "drama" },
  { text: "Love is giving someone the ability to destroy you, but trusting them not to.", source: "Criminal Minds", type: "drama" },
  { text: "To the living, we owe respect. But to the dead, we owe only the truth.", source: "Criminal Minds", type: "drama" },
  { text: "The truth is rarely pure and never simple.", source: "Criminal Minds", type: "drama" },
  { text: "We are made wise not by the recollection of our past, but by the responsibility of our future.", source: "Criminal Minds", type: "drama" },
  { text: "Your memory is a monster. It summons with will of its own. You think you have a memory but it has you.", source: "Criminal Minds", type: "drama" },
  { text: "It is a man's own mind, not his enemy or foe, that lures him to evil ways.", source: "Criminal Minds", type: "drama" },
  { text: "I know you're only trying to protect me, I get it, but knock it off.", source: "Criminal Minds", type: "drama" },
  { text: "Delay is the deadliest form of denial.", source: "Criminal Minds", type: "drama" },

  // White Collar (화이트 칼라 명대사!)
  { text: "There is a line. It's thin, but it's there. And sometimes, you have to step over it to do the right thing.", source: "White Collar", type: "drama" },
  { text: "If you want a happy ending, that depends, of course, on where you stop your story.", source: "White Collar", type: "drama" },
  { text: "I'm a white-collar criminal. We don't use violence, we use our brains and charm.", source: "White Collar", type: "drama" },
  { text: "I don't care about what you've done in your past. I only care about what you are doing right now.", source: "White Collar", type: "drama" },
  { text: "The best con is the one where they think it was their own brilliant idea.", source: "White Collar", type: "drama" },
  { text: "In my experience, the things we regret most in life are the risks we didn't take.", source: "White Collar", type: "drama" },
  { text: "Trust but verify. It is the gold standard for any partnership, especially ours.", source: "White Collar", type: "drama" },
  { text: "You know what they say about secrets: they're only secrets if you don't tell anyone.", source: "White Collar", type: "drama" },
  { text: "I don't lie. I just select which truths I choose to share.", source: "White Collar", type: "drama" },
  { text: "A true artist doesn't copy nature; he recreates it in his own vision.", source: "White Collar", type: "drama" },
  { text: "Sometimes you have to play the part to become the person.", source: "White Collar", type: "drama" },
  { text: "The key to a good disguise is not changing how you look, but changing how you carry yourself.", source: "White Collar", type: "drama" },
  { text: "We might be on opposite sides of the law, but we are looking at the exact same picture.", source: "White Collar", type: "drama" },
  { text: "Charm is the ability to make someone else feel like they are the only person in the room.", source: "White Collar", type: "drama" },
  { text: "There are no permanent enemies, only temporary alliances.", source: "White Collar", type: "drama" },

  // Grey's Anatomy (기타 드라마로 분류 변경 - 핵심 명대사만 남김)
  { text: "Knowing is better than wondering. Waking is better than sleeping. And even the biggest failure, even the worst, beats the hell out of never trying.", source: "Grey's Anatomy", type: "other_dramas" },
  { text: "You're my person.", source: "Grey's Anatomy", type: "other_dramas" },

  // Gilmore Girls (기타 드라마로 분류 변경 - 핵심 명대사만 남김)
  { text: "Oh, I can't stop drinking the coffee. I stop drinking the coffee, I stop doing the standing, walking, and the words putting into sentence doing.", source: "Gilmore Girls", type: "other_dramas" },
  { text: "Lorelai, this thing we're doing here — me, you. I just wanted you to know I'm in. I am all in.", source: "Gilmore Girls", type: "other_dramas" },

  // Suits (기타 드라마로 분류 변경 - 핵심 명대사만 남김)
  { text: "I don't have dreams. I have goals.", source: "Suits", type: "other_dramas" },
  { text: "When you're backed against the wall, break the damn thing down.", source: "Suits", type: "other_dramas" },

  // This Is Us (기타 드라마로 분류 변경 - 핵심 명대사만 남김)
  { text: "Grief is just love with nowhere left to go.", source: "This Is Us", type: "other_dramas" },
  { text: "Sometimes the bravest thing you can do is just keep going when you have every reason to stop.", source: "This Is Us", type: "other_dramas" },

  // Ted Lasso (기타 드라마로 분류 변경 - 핵심 명대사만 남김)
  { text: "Be curious, not judgmental.", source: "Ted Lasso", type: "other_dramas" },
  { text: "I believe in hope. I believe in believe.", source: "Ted Lasso", type: "other_dramas" },

  // Killing Eve
  { text: "I have been thinking about you. I think about you a lot, actually.", source: "Killing Eve", type: "drama" },
  { text: "You should never ignore a person who makes you feel things you cannot explain.", source: "Killing Eve", type: "drama" },

  // 9-1-1 Series (대사 대폭 확장!)
  { text: "Some people look for a savior. Others just look for someone to stand by them while they save themselves.", source: "9-1-1", type: "drama" },
  { text: "We don't get to choose how we're broken. We only get to choose how we put ourselves back together.", source: "9-1-1", type: "drama" },
  { text: "The hardest thing about this job isn't the things you see, it's the things you don't get to see: the happy endings.", source: "9-1-1", type: "drama" },
  { text: "Life is a series of emergencies. Some we survive, some we don't, but we always keep answering the call.", source: "9-1-1", type: "drama" },
  { text: "In the middle of a crisis, you don't rise to the occasion. You sink to the level of your training.", source: "9-1-1", type: "drama" },
  { text: "Fear is a reaction. Courage is a decision.", source: "9-1-1", type: "drama" },
  { text: "Sometimes, the only way to find yourself is to get a little lost in the service of others.", source: "9-1-1", type: "drama" },
  { text: "We are all first responders to our own lives. Sometimes we just need a little backup.", source: "9-1-1", type: "drama" },
  { text: "There is no manual for grief. You just have to feel it until you can breathe again.", source: "9-1-1", type: "drama" },
  { text: "You can't save everyone. But you can save the person right in front of you.", source: "9-1-1", type: "drama" },
  { text: "Being a first responder means walking into the fire when everyone else is running out.", source: "9-1-1", type: "drama" },
  { text: "Family isn't just about blood. It's about who stands beside you when the alarm goes off.", source: "9-1-1", type: "drama" },
  { text: "Every rescue is a second chance, not just for the victim, but for us.", source: "9-1-1", type: "drama" },
  { text: "No matter how dark the night, the sun always rises. We just have to make it to morning.", source: "9-1-1", type: "drama" },
  { text: "Hope is the strongest anchor we have when the ground starts shaking.", source: "9-1-1", type: "drama" },
  { text: "In our line of work, you don't get to look back. You just focus on the next step.", source: "9-1-1", type: "drama" },
  { text: "The sirens are a promise to the city: you are not alone, we are coming.", source: "9-1-1", type: "drama" },
  { text: "Sometimes a miracle is just a group of people who refuse to give up.", source: "9-1-1", type: "drama" },
  { text: "You don't fight fire with fire. You fight it with water, patience, and a whole lot of grit.", source: "9-1-1: Lone Star", type: "drama" },
  { text: "Sometimes you have to let the fire burn itself out before you can start rebuilding from the ashes.", source: "9-1-1: Lone Star", type: "drama" },
  { text: "9-1-1, what is your emergency? We have multiple rescue units responding to the scene.", source: "9-1-1: Nashville", type: "drama" },
  { text: "In Nashville, music isn't the only thing that saves lives. It's the community of first responders standing watch.", source: "9-1-1: Nashville", type: "drama" },
  { text: "When the sirens echo down Broadway, you know help is on the way. We never ignore a single call.", source: "9-1-1: Nashville", type: "drama" },

  // Will Trent (대사 확장!)
  { text: "I grew up in the system. The system doesn't forget you, and you certainly never forget the system.", source: "Will Trent", type: "drama" },
  { text: "Details don't lie. People do, every single day. That's why I look at the walls and the floor first.", source: "Will Trent", type: "drama" },
  { text: "We are all carrying bags filled with rocks we didn't ask for. The trick is finding someone to help you carry yours.", source: "Will Trent", type: "drama" },
  { text: "A crime scene is a story told in whispers. You just have to know how to listen.", source: "Will Trent", type: "drama" },
  { text: "Dyslexia doesn't mean I can't read the world. It just means I read it differently than everyone else.", source: "Will Trent", type: "drama" },
  { text: "You don't get to choose your scars, but you do get to decide how you wear them.", source: "Will Trent", type: "drama" },
  { text: "Behind every cold case is a family still waiting for the warmth of justice.", source: "Will Trent", type: "drama" },
  { text: "Sometimes the people who are the hardest to love are the ones who need it the most.", source: "Will Trent", type: "drama" },
  { text: "The truth isn't always comfortable, but it's the only thing that keeps us anchored.", source: "Will Trent", type: "drama" },
  { text: "You can't solve a mystery by staying on the outside. You have to walk right into the middle of the mess.", source: "Will Trent", type: "drama" },

  // Once Upon a Time (대사 대폭 확장!)
  { text: "Believing in even the possibility of a happy ending is a very powerful thing.", source: "Once Upon a Time", type: "drama" },
  { text: "Magic always comes with a price, dearie.", source: "Once Upon a Time", type: "drama" },
  { text: "True love is the most powerful magic of all, and it can break any curse.", source: "Once Upon a Time", type: "drama" },
  { text: "A hero is someone who has to make the tough choices, even when it means sacrificing their own happiness.", source: "Once Upon a Time", type: "drama" },
  { text: "People are gonna tell you who you are your whole life. You just gotta punch back and say, 'No, this is who I am.'", source: "Once Upon a Time", type: "drama" },
  { text: "All magic comes with a price, but love is a force that is completely free.", source: "Once Upon a Time", type: "drama" },
  { text: "The only way to overcome fear is to face it head-on, even if you are terrified.", source: "Once Upon a Time", type: "drama" },
  { text: "Happy endings aren't handed to us. We have to fight for them, day after day.", source: "Once Upon a Time", type: "drama" },
  { text: "We all have darkness inside us, but we also have the choice to let the light shine through.", source: "Once Upon a Time", type: "drama" },
  { text: "Even the most broken hearts can find a way to beat again if they are open to hope.", source: "Once Upon a Time", type: "drama" },
  { text: "A villain is just a victim whose story hasn't been told yet.", source: "Once Upon a Time", type: "drama" },
  { text: "You can't run away from who you are. The past has a way of catching up to you.", source: "Once Upon a Time", type: "drama" },
  { text: "Love doesn't mean you don't get hurt. It means you care enough to take the risk anyway.", source: "Once Upon a Time", type: "drama" },
  { text: "Sometimes the best way to save someone is to let them save themselves.", source: "Once Upon a Time", type: "drama" },
  { text: "Belief is a choice. You have to believe in the magic before you can see it.", source: "Once Upon a Time", type: "drama" },
  { text: "There is no such thing as a perfect hero, just people doing the best they can.", source: "Once Upon a Time", type: "drama" },
  { text: "We write our own stories. No one else gets to hold the pen.", source: "Once Upon a Time", type: "drama" },
  { text: "The world is full of curses, but it is also full of people willing to break them.", source: "Once Upon a Time", type: "drama" },
  { text: "If you want to change your fate, you have to be willing to change yourself.", source: "Once Upon a Time", type: "drama" },
  { text: "Family is more than a name; it is the promise to never leave each other behind.", source: "Once Upon a Time", type: "drama" },

  // Disney & Films
  { text: "Remember who you are.", source: "The Lion King", type: "disney" },
  { text: "Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.", source: "The Lion King", type: "disney" },
  { text: "Ohana means family. Family means nobody gets left behind or forgotten.", source: "Lilo & Stitch", type: "disney" },
  { text: "To infinity and beyond!", source: "Toy Story", type: "disney" },
  { text: "Even miracles take a little time.", source: "Cinderella", type: "disney" },
  { text: "The flower that blooms in adversity is the most rare and beautiful of all.", source: "Mulan", type: "disney" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", source: "Winnie the Pooh", type: "disney" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", source: "Pride & Prejudice", type: "film" },
  { text: "Only the deepest love will persuade me into matrimony, which is why I will end up an old maid.", source: "Pride & Prejudice", type: "film" },
  { text: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", source: "Pride & Prejudice", type: "film" },
  { text: "I could easily forgive his pride, if he had not mortified mine.", source: "Pride & Prejudice", type: "film" },
  { text: "There is a stubbornness about me that never can bear to be frightened at the will of others.", source: "Pride & Prejudice", type: "film" },
  { text: "My courage always rises with every attempt to intimidate me.", source: "Pride & Prejudice", type: "film" },
  { text: "Angry people are not always wise.", source: "Pride & Prejudice", type: "film" },
  { text: "I like myself the way I am.", source: "Penelope (2006)", type: "film" },
  { text: "It's not the power of the curse, it's the power you give it.", source: "Penelope (2006)", type: "film" },
  { text: "It's not about what they see. It's about what you choose to show them.", source: "Penelope (2006)", type: "film" },
  { text: "I'm not a monster. I'm just a person who wants to be loved for who I am.", source: "Penelope (2006)", type: "film" },
  { text: "This is my story. This is the sacrifice my father made. This was his gift to me.", source: "Life is Beautiful (1997)", type: "film" },
  { text: "Nothing is more necessary than the unnecessary.", source: "Life is Beautiful (1997)", type: "film" },
  { text: "We'll be together. Don't worry. I am right here by your side.", source: "Life is Beautiful (1997)", type: "film" },
  { text: "You can lose everything, but you must never lose your smile and your hope.", source: "Life is Beautiful (1997)", type: "film" },
  { text: "When the Lord closes a door, somewhere He opens a window.", source: "The Sound of Music", type: "film" },
  { text: "The hills are alive with the sound of music, with songs they have sung for a thousand years.", source: "The Sound of Music", type: "film" },
  { text: "A bell is no bell 'til you ring it. A song is no song 'til you sing it. And love in your heart wasn't put there to stay.", source: "The Sound of Music", type: "film" },
  { text: "A heart that is full of love has no room for fear or despair.", source: "The Sound of Music", type: "film" },
  { text: "My heart wants to sing every song it hears, and the hills are calling my name.", source: "The Sound of Music", type: "film" },

  // Musical & Theater (뮤지컬 & 연극 명대사 신규 탑재!)
  { text: "I am not throwing away my shot. I am just like my country, I am young, scrappy and hungry.", source: "Hamilton (Musical)", type: "musical" },
  { text: "Talk less. Smile more. Don't let them know what you're against or what you're for.", source: "Hamilton (Musical)", type: "musical" },
  { text: "Because I knew you, I have been changed for good.", source: "Wicked (Musical)", type: "musical" },
  { text: "Everyone deserves the chance to fly, and you're not gonna bring me down.", source: "Wicked (Musical)", type: "musical" },
  { text: "Do you hear the people sing? Singing the song of angry men?", source: "Les Misérables (Musical)", type: "musical" },
  { text: "To love another person is to see the face of God.", source: "Les Misérables (Musical)", type: "musical" },
  { text: "No day but today. There is no lease on life, but we can make this moment last.", source: "Rent (Musical)", type: "musical" },
  { text: "How do you measure a year in the life? Measure in love, measure in sunsets, measure in cups of coffee.", source: "Rent (Musical)", type: "musical" },
  { text: "The Phantom of the Opera is there, inside your mind.", source: "The Phantom of the Opera", type: "musical" },
  { text: "Think of me, think of me fondly, when we've said goodbye.", source: "The Phantom of the Opera", type: "musical" },
  { text: "All the world's a stage, and all the men and women merely players.", source: "As You Like It (Play)", type: "play" },
  { text: "To be, or not to be, that is the question.", source: "Hamlet (Play)", type: "play" },
  { text: "What's in a name? That which we call a rose by any other name would smell as sweet.", source: "Romeo and Juliet (Play)", type: "play" },
  { text: "We are such stuff as dreams are made on, and our little life is rounded with a sleep.", source: "The Tempest (Play)", type: "play" },

  // Famous Quotes (유명인 명언 신규 탑재!)
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.", source: "Steve Jobs", type: "quotes" },
  { text: "In the middle of difficulty lies opportunity.", source: "Albert Einstein", type: "quotes" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", source: "Eleanor Roosevelt", type: "quotes" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", source: "Winston Churchill", type: "quotes" },
  { text: "It is during our darkest moments that we must focus to see the light.", source: "Aristotle", type: "quotes" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", source: "Ralph Waldo Emerson", type: "quotes" },
  { text: "Believe you can and you're halfway there.", source: "Theodore Roosevelt", type: "quotes" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", source: "Franklin D. Roosevelt", type: "quotes" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", source: "Mother Teresa", type: "quotes" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", source: "Nelson Mandela", type: "quotes" },
  { text: "You must be the change you wish to see in the world.", source: "Mahatma Gandhi", type: "quotes" },
  { text: "Stay hungry, stay foolish.", source: "Steve Jobs", type: "quotes" },

  // TED Talks (테드 강연 명대사 신규 탑재!)
  { text: "My favorite definition of leadership is this: It is about making others better as a result of your presence.", source: "Sheryl Sandberg (TED)", type: "ted" },
  { text: "Vulnerability is not winning or losing; it is having the courage to show up and be seen when we have no control.", source: "Brené Brown (TED)", type: "ted" },
  { text: "Gritty people have a growth mindset: they believe that the ability to learn is not fixed, that it can change with effort.", source: "Angela Duckworth (TED)", type: "ted" },
  { text: "Your body language shapes who you are. Fake it until you become it.", source: "Amy Cuddy (TED)", type: "ted" },
  { text: "The single most important ingredient on this scenic journey is the belief that you are enough.", source: "TED Talk", type: "ted" },
  { text: "We do not need a handful of people doing zero waste perfectly. We need millions doing it imperfectly.", source: "TED Talk", type: "ted" },
  { text: "To find what you love, you must first discover what you can live without.", source: "TED Talk", type: "ted" },
  { text: "The best way to predict your future is to create it, not wait for it to happen.", source: "TED Talk", type: "ted" },
  { text: "The most powerful thing you can do to change the world is to listen to someone else's story with empathy.", source: "TED Talk", type: "ted" },
  { text: "We are all born with a unique gift, and our only job in this life is to unwrap it and share it.", source: "TED Talk", type: "ted" },
  { text: "Your perspective is the most unique thing about you, so do not try to fit in when you were born to stand out.", source: "TED Talk", type: "ted" },
  { text: "The difference between who you are and who you want to be is what you do.", source: "TED Talk", type: "ted" }
];

export const gutenbergSources: GutenbergSource[] = [
  { repo: "Pride-and-Prejudice_1342", file: "1342.txt", title: "Pride and Prejudice", author: "Jane Austen" },
  { repo: "Sense-and-Sensibility_161", file: "161.txt", title: "Sense and Sensibility", author: "Jane Austen" },
  { repo: "Persuasion_105", file: "105.txt", title: "Persuasion", author: "Jane Austen" },
  { repo: "The-Adventures-of-Sherlock-Holmes_1661", file: "1661.txt", title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle" },
  { repo: "Hamlet-Prince-of-Denmark_1524", file: "1524.txt", title: "Hamlet", author: "William Shakespeare" },
  { repo: "Romeo-and-Juliet_1513", file: "1513.txt", title: "Romeo and Juliet", author: "William Shakespeare" },
  { repo: "Alice-s-Adventures-in-Wonderland_11", file: "11.txt", title: "Alice's Adventures in Wonderland", author: "Lewis Carroll" },
  { repo: "The-Wonderful-Wizard-of-Oz_55", file: "55.txt", title: "The Wonderful Wizard of Oz", author: "L. Frank Baum" },
  { repo: "A-Tale-of-Two-Cities_98", file: "98.txt", title: "A Tale of Two Cities", author: "Charles Dickens" },
  { repo: "Jane-Eyre_1260", file: "1260.txt", title: "Jane Eyre", author: "Charlotte Bronte" },
  { repo: "The-Picture-of-Dorian-Gray_174", file: "174.txt", title: "The Picture of Dorian Gray", author: "Oscar Wilde" }
];
